apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
        metadata:
         labels:
           app: wordpress
           tier: frontend 
        spec:
            containers:      
              - name: wordpress
                image: wordpress:php7.1-apache    
                env:  
                 - name: WORDPRESS_DB_HOST
                   value: mysql-svc
                 - name: WORDPRESS_DB_PASSWORD
                   valueFrom:
                    secretKeyRef:
                      key: password
                      name: myaql-pass
                ports: 
                  - containerPort: 80
                volumeMounts:
                  - mountPath: /var/www/html
                    name: wordpress-storage
            volumes:  
             - name: wordpress-storage
               persistentVolumeClaim:
                 claimName: wordpress-efs-pvc
